/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/geojson/reaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReaches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geojson/points/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPointSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geojson/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetStations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reaches/{sourceId}/{stationKey}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReachHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        CircuitState: 0 | 1 | 2;
        HistoryPoint: {
            /** Format: date-time */
            measuredAt?: string;
            /** Format: double */
            valueCm?: number;
            level?: string | null;
        };
        ReachFeature: {
            readonly type?: string | null;
            geometry: unknown;
            properties: components["schemas"]["ReachProperties"];
        };
        ReachFeatureCollection: {
            readonly type?: string | null;
            meta: components["schemas"]["ReachMeta"];
            features: components["schemas"]["ReachFeature"][] | null;
        };
        ReachHistory: {
            sourceId: string | null;
            stationKey: string | null;
            name: string | null;
            river?: string | null;
            /** Format: int32 */
            days: number;
            points: components["schemas"]["HistoryPoint"][] | null;
            thresholds?: components["schemas"]["ReachThreshold"][] | null;
            thresholdsDefinedBy?: string | null;
            agencyName: string | null;
            /** Format: date-time */
            collectingSince?: string | null;
        };
        ReachMeta: {
            sourceId: string | null;
            /** Format: date-time */
            fetchedAt: string;
            /** Format: date-time */
            generatedAt: string;
            /** Format: int32 */
            reachCount: number;
            /** Format: int32 */
            knownCount: number;
            /** Format: int32 */
            unknownCount: number;
            /** Format: int32 */
            measuredCount: number;
            /** Format: int32 */
            withoutGeometry: number;
        };
        ReachObservation: {
            parameter?: string | null;
            label?: string | null;
            /** Format: double */
            value?: number;
            unit?: string | null;
            /** Format: date-time */
            measuredAt?: string;
            /** Format: int64 */
            ageMinutes?: number;
        };
        ReachProperties: {
            sourceId: string | null;
            stationKey: string | null;
            name: string | null;
            river?: string | null;
            level: string | null;
            levelLabel: string | null;
            color: string | null;
            statusLabelOriginal: string | null;
            /** Format: double */
            valueCm?: number | null;
            /** Format: double */
            gaugeZeroMetres?: number | null;
            /** Format: date-time */
            measuredAt?: string | null;
            /** Format: date-time */
            fetchedAt: string;
            /** Format: int64 */
            ageMinutes?: number | null;
            /** Format: int64 */
            expectedIntervalMinutes: number;
            intervalIsMeasured: boolean;
            /** Format: int64 */
            publicationLagMinutes: number;
            /** Format: double */
            ageRatio?: number | null;
            /** Format: double */
            previousValueCm?: number | null;
            /** Format: date-time */
            previousMeasuredAt?: string | null;
            /** Format: double */
            changeCm?: number | null;
            /** Format: int64 */
            changeOverMinutes?: number | null;
            publishedTrend?: string | null;
            publishedTrendLabel?: string | null;
            agencyName: string | null;
            agencyUrl: string | null;
            sourceUrl?: string | null;
            noDataReason?: string | null;
            thresholds?: components["schemas"]["ReachThreshold"][] | null;
            observations?: components["schemas"]["ReachObservation"][] | null;
            thresholdsDefinedBy?: string | null;
        };
        ReachThreshold: {
            label?: string | null;
            /** Format: double */
            valueCm?: number;
            level?: string | null;
            labelOriginal?: string | null;
        };
        SourceStatus: {
            sourceId: string | null;
            agencyName: string | null;
            /** Format: date-time */
            lastAttemptAt?: string | null;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            /** Format: int32 */
            consecutiveFailures?: number;
            circuit?: components["schemas"]["CircuitState"];
            lastFailureReason?: string | null;
            /** Format: int32 */
            knownCount?: number;
            /** Format: int32 */
            unknownCount?: number;
            /** Format: int32 */
            measuredCount?: number;
            /** Format: int32 */
            withoutMeasurementCount?: number;
            clockEvidence: string | null;
            readonly isHealthy?: boolean;
        };
        StationFeature: {
            geometry: unknown;
            properties: components["schemas"]["StationProperties"];
        };
        StationFeatureCollection: {
            meta: components["schemas"]["StationMeta"];
            features: components["schemas"]["StationFeature"][] | null;
        };
        StationMeta: {
            sourceId: string | null;
            /** Format: date-time */
            fetchedAt: string;
            /** Format: int32 */
            stationCount: number;
            /** Format: int32 */
            withoutGeometry: number;
            /** Format: int32 */
            withoutGaugeZero: number;
            /** Format: int32 */
            withoutName: number;
        };
        StationProperties: {
            sourceId: string | null;
            stationKey?: string | null;
            name: string | null;
            location?: string | null;
            stationType?: string | null;
            /** Format: double */
            gaugeZero?: number | null;
            /** Format: int32 */
            gaugeBoardCount?: number | null;
            agencyName: string | null;
            agencyUrl: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetReaches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["ReachFeatureCollection"];
                };
            };
        };
    };
    GetPointSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["ReachFeatureCollection"];
                };
            };
        };
    };
    GetStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["StationFeatureCollection"];
                };
            };
        };
    };
    GetReachHistory: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                sourceId: string;
                stationKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachHistory"];
                };
            };
        };
    };
    GetSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
}
