/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/geojson/reaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReaches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        CircuitState: 0 | 1 | 2;
        ReachFeature: {
            readonly type?: string | null;
            geometry: unknown;
            properties: components["schemas"]["ReachProperties"];
        };
        ReachFeatureCollection: {
            readonly type?: string | null;
            meta: components["schemas"]["ReachMeta"];
            features: components["schemas"]["ReachFeature"][] | null;
        };
        ReachMeta: {
            sourceId: string | null;
            /** Format: date-time */
            fetchedAt: string;
            /** Format: date-time */
            generatedAt: string;
            /** Format: int32 */
            reachCount: number;
            /** Format: int32 */
            knownCount: number;
            /** Format: int32 */
            unknownCount: number;
            /** Format: int32 */
            withoutGeometry: number;
        };
        ReachProperties: {
            sourceId: string | null;
            stationKey: string | null;
            name: string | null;
            river?: string | null;
            level: string | null;
            levelLabel: string | null;
            color: string | null;
            statusLabelOriginal: string | null;
            /** Format: double */
            valueCm?: number | null;
            /** Format: date-time */
            measuredAt?: string | null;
            /** Format: date-time */
            fetchedAt: string;
            /** Format: int64 */
            ageMinutes?: number | null;
            /** Format: int64 */
            expectedIntervalMinutes: number;
            /** Format: double */
            ageRatio?: number | null;
            agencyName: string | null;
            agencyUrl: string | null;
            sourceUrl?: string | null;
            noDataReason?: string | null;
            thresholds?: components["schemas"]["ReachThreshold"][] | null;
            thresholdsDefinedBy?: string | null;
        };
        ReachThreshold: {
            label?: string | null;
            /** Format: double */
            valueCm?: number;
            level?: string | null;
        };
        SourceStatus: {
            sourceId: string | null;
            agencyName: string | null;
            /** Format: date-time */
            lastAttemptAt?: string | null;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            /** Format: int32 */
            consecutiveFailures?: number;
            circuit?: components["schemas"]["CircuitState"];
            lastFailureReason?: string | null;
            /** Format: int32 */
            knownCount?: number;
            /** Format: int32 */
            unknownCount?: number;
            clockEvidence: string | null;
            readonly isHealthy?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetReaches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["ReachFeatureCollection"];
                };
            };
        };
    };
    GetSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
}
