<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Vodostaji.Ingest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Vodostaji.Core/Vodostaji.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.7.0" />
  </ItemGroup>

</Project>
