// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vodostaji.Data;

#nullable disable

namespace Vodostaji.Data.Migrations
{
    [DbContext(typeof(VodostajiDbContext))]
    [Migration("20260805000106_AddPublicationLag")]
    partial class AddPublicationLag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vodostaji.Data.MeasurementRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValueCm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StationKey", "MeasuredAt")
                        .IsUnique()
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_measurements_station_time_desc");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("Vodostaji.Data.StationRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<string>("StationKey")
                        .HasColumnType("text");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExpectedIntervalSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GaugeZero")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PublicationLagSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("River")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("SourceId", "StationKey");

                    b.HasIndex("SourceId");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("Vodostaji.Data.StationStateRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<string>("StationKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTimeOffset?>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoDataReason")
                        .HasColumnType("text");

                    b.Property<string>("StatusLabelOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdsDefinedBy")
                        .HasColumnType("text");

                    b.Property<string>("ThresholdsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueCm")
                        .HasColumnType("numeric");

                    b.HasKey("SourceId", "StationKey");

                    b.HasIndex("Level");

                    b.HasIndex("SourceId");

                    b.ToTable("station_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_station_states_unknown_never_normal", "\"ValueCm\" IS NOT NULL OR \"Level\" = 'Unknown'");

                            t.HasCheckConstraint("ck_station_states_value_needs_time", "(\"ValueCm\" IS NULL) = (\"MeasuredAt\" IS NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
